### ISSUE TITLE
Lodash version

### ISSUE THREAD

**Issue by stevage** [xingrz/node-contributors#9]
Version 4 of lodash doesn't have a 'unique' function.

Probably you should use `~` instead of `>=` in your package.json.

**Comment by JamieMason** [comment]
Pull Request opened: https://github.com/xingrz/node-contributors/pull/10

/cc @stevage @fengmk2 @xingrz

**Comment by fengmk2** [comment]
Fixed on af957926eef10ed341b1142150f787464bf87544, thanks to @JamieMason :100:

**Comment by JamieMason** [comment]
Thanks @fengmk2
